server:
  port: 8021
  waitTimeInMsWhenSyncEmpty: 4000
eureka:
  instance:
    hostname: byg-eureka-server1
    prefer-ip-address: true
    ip-address: 192.168.29.129
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address}:8022/eureka/
