server:
  port: 8022
eureka:
  instance:
    hostname: byg-eureka-server2
    prefer-ip-address: true
    ip-address: 192.168.29.129
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address}:8021/eureka/,http://${eureka.instance.ip-address}:8023/eureka/
